# Keep rules for app + plugins.

# Suppress R8 missing-class warnings from optional MediaPipe protos.
# (Generated by AGP in build/app/outputs/mapping/*/missing_rules.txt)
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate
